# Generated by Django 5.2.1 on 2025-06-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_note_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meat_type',
            field=models.CharField(max_length=30),
        ),
    ]
